version: '3'

services:
  db:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3356:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    platform: linux/x86_64 # M1チップ対応のため追記
    image: wordpress:latest
    volumes:
    - "$PWD/src/wordpress:/var/www/html"
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: phpmyadmin/phpmyadmin:latest
    #container_name: "phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
  nuxtjs:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: node:16
    user: node
    working_dir: /home/node
    tty: true
    ports:
      - "${NUXTJS_PORT}:3000"
    volumes:
      - "$PWD/src/node:/home/node/for-wp-rest-api"
volumes:
    db_data: